name: Build Android AAR

on:
  workflow_dispatch:    # 允许手动触发构建
    inputs:
      target:
        description: '目标架构'
        required: true
        default: 'android/arm64,android/arm'
        type: choice
        options:
          - 'android/arm64,android/arm'
          - 'android/arm64'
          - 'android/arm'
      androidapi:
        description: 'Android API Level'
        required: true
        default: '21'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Go 环境
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: 设置 Java 环境
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: 设置 Android SDK
        uses: android-actions/setup-android@v2

      - name: 安装 NDK
        run: |
          sdkmanager --install "ndk;25.2.9519653"
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: 安装 gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest
          gomobile init

      - name: 构建 AAR
        run: |
          gomobile bind -v \
            -target=${{ inputs.target }} \
            -androidapi=${{ inputs.androidapi }} \
            -ldflags="-s -w" \
            -trimpath \
            -o build/tun2socks.aar \
            -tags="android" \
            ./mobile

      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: tun2socks-aar
          path: build/tun2socks.aar
          retention-days: 7
